In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import mglearn
from IPython.display import display
plt.rc('font', family='Ubuntu')

In [17]:
df = pd.read_json('forward_data.json')

In [18]:
df

,count,name,places
0,4,"North Slope,","[('-153.8220681', '69.5335129', 'boundary', 'a..."
1,10,"Alaska,","[('-149.680909', '64.4459613', 'boundary', 'ad..."
2,3,"United States of America,","[('-100.4458825', '39.7837304', 'boundary', 'a..."
3,1,"North Slope, Alaska","[('-153.8220681', '69.5335129', 'boundary', 'a..."
4,4,"North Slope, United States of America","[('-153.8220681', '69.5335129', 'boundary', 'a..."
5,10,"Alaska, United States of America","[('-149.680909', '64.4459613', 'boundary', 'ad..."
6,1,"North Slope, Alaska, United States of America","[('-153.8220681', '69.5335129', 'boundary', 'a..."
7,2,"Мильковское сельское поселение,","[('159.06556293848', '55.1187873', 'boundary',..."
8,1,"Мильковский район,","[('158.915445118642', '54.8696435', 'boundary'..."
9,2,"Камчатский край,","[('160.08132826863', '57.80511375', 'boundary'..."
10,7,"ДФО,","[('137.38882719604', '59.3334319', 'boundary',..."
11,10,"РФ,","[('97.7453061', '64.6863136', 'boundary', 'adm..."
12,1,"Мильковское сельское поселение, Мильковский р...","[('159.06556293848', '55.1187873', 'boundary',..."
13,1,"Мильковское сельское поселение, Камчатский край","[('159.06556293848', '55.1187873', 'boundary',..."
14,1,"Мильковское сельское поселение, ДФО","[('159.06556293848', '55.1187873', 'boundary',..."
15,2,"Мильковское сельское поселение, РФ","[('159.06556293848', '55.1187873', 'boundary',..."
16,1,"Мильковский район, Камчатский край","[('158.915445118642', '54.8696435', 'boundary'..."
17,1,"Мильковский район, ДФО","[('158.915445118642', '54.8696435', 'boundary'..."
18,1,"Мильковский район, РФ","[('158.915445118642', '54.8696435', 'boundary'..."
19,2,"Камчатский край, ДФО","[('160.08132826863', '57.80511375', 'boundary'..."
20,2,"Камчатский край, РФ","[('160.08132826863', '57.80511375', 'boundary'..."
21,1,"ДФО, РФ","[('137.38882719604', '59.3334319', 'boundary',..."
22,1,"Мильковское сельское поселение, Мильковский р...","[('159.06556293848', '55.1187873', 'boundary',..."
23,1,"Мильковское сельское поселение, Мильковский р...","[('159.06556293848', '55.1187873', 'boundary',..."
24,1,"Мильковское сельское поселение, Мильковский р...","[('159.06556293848', '55.1187873', 'boundary',..."
25,1,"Мильковское сельское поселение, Камчатский кр...","[('159.06556293848', '55.1187873', 'boundary',..."
26,1,"Мильковское сельское поселение, Камчатский кр...","[('159.06556293848', '55.1187873', 'boundary',..."
27,1,"Мильковское сельское поселение, ДФО, РФ","[('159.06556293848', '55.1187873', 'boundary',..."
28,1,"Мильковский район, Камчатский край, ДФО","[('158.915445118642', '54.8696435', 'boundary'..."
29,1,"Мильковский район, Камчатский край, РФ","[('158.915445118642', '54.8696435', 'boundary'..."
...,...,...,...
440,1,"Carretera Estatal Miacatlan - Palpan, Miacatl...","[('-99.401216', '18.833021', 'highway', 'secon..."
441,1,"Palo Grande, Miacatlán, Morelos, 62600, M...","[('-99.4041976', '18.8336271', 'place', 'villa..."
442,1,"Carretera Estatal Miacatlan - Palpan, Palo Gr...","[('-99.401216', '18.833021', 'highway', 'secon..."
443,2,"Archipiélago de San Andrés,","[('-81.6140750764522', '12.38051665', 'boundar..."
444,2,"Providencia y Santa Catalina Colombia,","[('-81.6140750764522', '12.38051665', 'boundar..."
445,10,"Colombia,","[('-73.783892', '2.8894434', 'boundary', 'admi..."
446,0,"Archipiélago de San Andrés, Providencia y San...",[]
447,2,"Archipiélago de San Andrés, Colombia","[('-81.6140750764522', '12.38051665', 'boundar..."
448,1,"Providencia y Santa Catalina Colombia, Colombia","[('-81.6140750764522', '12.38051665', 'boundar..."
449,0,"Archipiélago de San Andrés, Providencia y San...",[]
450,2,"Simpson Desert,","[('136.951049821636', '-25.45578', 'natural', ..."
451,1,"Pastoral Unincorporated Area,","[('137.019137252743', '-30.11880435', 'boundar..."
452,1,"South Australia,","[('135.6301212', '-30.5343665', 'boundary', 'a..."
453,10,"5734,","[('21.5491088945964', '46.8943353', 'boundary'..."
454,10,"Australia,","[('134.755', '-24.7761086', 'boundary', 'admin..."
455,1,"Simpson Desert, Pastoral Unincorporated Area","[('137.291903346937', '-26.85125515', 'boundar..."
456,1,"Simpson Desert, South Australia","[('137.291903346937', '-26.85125515', 'boundar..."
457,1,"Simpson Desert, 5734","[('137.291903346937', '-26.85125515', 'boundar..."
458,2,"Simpson Desert, Australia","[('136.951049821636', '-25.45578', 'natural', ..."
459,1,"Pastoral Unincorporated Area, South Australia","[('137.019137252743', '-30.11880435', 'boundar..."
460,1,"Pastoral Unincorporated Area, 5734","[('135.552417357861', '-26.8470951301045', 'pl..."
461,1,"Pastoral Unincorporated Area, Australia","[('137.019137252743', '-30.11880435', 'boundar..."
462,1,"South Australia, 5734","[('135.552417357861', '-26.8470951301045', 'pl..."
463,1,"South Australia, Australia","[('135.6301212', '-30.5343665', 'boundary', 'a..."
464,1,"5734, Australia","[('135.552417357861', '-26.8470951301045', 'pl..."
465,1,"Simpson Desert, Pastoral Unincorporated Area,...","[('137.291903346937', '-26.85125515', 'boundar..."
466,1,"Simpson Desert, Pastoral Unincorporated Area,...","[('137.291903346937', '-26.85125515', 'boundar..."
467,1,"Simpson Desert, Pastoral Unincorporated Area,...","[('137.291903346937', '-26.85125515', 'boundar..."
468,1,"Simpson Desert, South Australia, 5734","[('137.291903346937', '-26.85125515', 'boundar..."
469,1,"Simpson Desert, South Australia, Australia","[('137.291903346937', '-26.85125515', 'boundar..."

In [19]:
df.loc[1]['name']

' Alaska, '

In [27]:
list_of_sames = []
header = ['name1', 'name2']

In [28]:
for i in range(df.shape[0]):
    for j in range(df.shape[0]):
        if df.loc[i]['count'] == 1:
            if (df.loc[i]['places'] == df.loc[j]['places']) and (i != j) and (df.loc[i]['name'] != df.loc[j]['name']):
                list_of_sames.append((df.loc[i]['name'], df.loc[j]['name']))

In [35]:
newdf = pd.DataFrame.from_records(list_of_sames, columns=header)
newdf.to_json('full_same_data.json', force_ascii=False, orient='records')

In [31]:
newnewdf = newdf.sample(100)

In [34]:
newnewdf.to_json('test_same_data.json', force_ascii=False, orient='records')

In [37]:
df = pd.read_excel('reverse_data_edited.xlsx')

In [39]:
df.to_json('full_reverse_data.json', force_ascii=False, orient='records')
df.sample(100).to_json('test_reverse_data.json', force_ascii=False, orient='records')
df.sample(10).to_json('small_reverse_data.json', force_ascii=False, orient='records')